[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/review/:id"
  to = "/.netlify/functions/review-meta/:id"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
